### ISSUE TITLE
Review and finalize storage strategy

### ISSUE THREAD

**Issue by sebastiangreger** [sebastiangreger/kirby3-commentions#13]
Before pushing the 1.0 version to public beta, it would be important to be 100% sure the data storage concept is final. Since 0.x users have to migrate anyways, which always comes with risk, it would be preferable that there won't be further changes to this structure in the forseeable future.

In the current draft, comments are stored in a `_commentions.txt` text file in the same folder as the page content, containing a field "Comments" with YAML-formatted data; the same file also holds the webmention backlog in field "Queue", in the future more fields might follow. (I moved away from the idea of storing each comment/webmention in a separate file, as with that kind of micro-interactions, this could lead to a unwieldy amount of files on a popular website - e.g. imagine every "like" creating a separate file.)

Simple example, with two comments and one unprocessed webmention in the queue:

```
Comments:

- 
  name: Testy McTesting
  status: approved
  text: Lorem ipsum
  timestamp: 2020-04-16 14:40
  type: comment
  uid: r3qr4k0mba
- 
  name: John Doe
  status: pending
  source: https://example.com/blog-post
  timestamp: 2020-04-16 16:11
  type: like
  uid: v9hahnc8pg

----

Queue:

- 
  source: https://example.com/my-blog-post
  target: >
    http://test2.test/notes/exploring-the-universe
  timestamp: 1586966853
  uid: fvbyya8xm5
```

For multi-language sites, a "language" field is added to each entry (if the language field is missing, the comment is considered to be for all applicable languages):

```
Comments:

- 
  language: en
  name: Testy McTesting
  status: approved
  text: Lorem ipsum
  timestamp: 2020-04-16 14:40
  type: comment
  uid: r3qr4k0mba
```

Since virtual pages do not have a folder to place the file in, we instead search for the nearest ancestor that is a "real" page (can be the parent, grandparent, or even further up). For this ancestor page, a `_commentions` folder is created, which then replicates the path to the page by subfolders and places the regular `_commentions.txt` file.

So for example virtual page `bicycles/mountainbike/red` with both `mountainbike` and `red` being virtual pages, would create the following structure:

```
content/
  1_bicycles/                <<< a physical page, with multiple levels of virtual pages below
    products.txt
    photo.jpg
    photo.jpg.txt
    _commentions.txt         <<< comment storage for the physical page
    _commentions/            <<< folder created in the ancestor's folder
      mountainbike/          <<< path replicated in folders
        red/
          _commentions.txt   <<< comment storage for the virtual page
```

Would it be more consistent to also make use of the `_commentions` folder for all physical pages? I.e. for a regular page (without any virtual page shenanigans), the structure would be:

```
content/
  1_blog/
    article.txt
    photo.jpg
    photo.jpg.txt
    _commentions/
      _commentions.txt
```

This wouldn't affect the performance at all, but would be more consistent?

Any other thoughts/issues that come to mind regarding the above storage logic? Ping @fabianmichael
